FROM oven/bun:1.3.9-alpine

WORKDIR /app

RUN apk add --no-cache libc6-compat wget

COPY bun.lock package.json turbo.json ./
COPY apps/api/package.json ./apps/api/
COPY apps/web/package.json ./apps/web/
COPY packages/ ./packages/
RUN bun install

EXPOSE 5000

CMD ["bun", "run", "--filter", "api", "dev"]
